/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockLayer: typeof import('./src/components/BlockLayer.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Dark: typeof import('./src/components/Dark.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FileSelector: typeof import('./src/components/FileSelector.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Language: typeof import('./src/components/Language.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    QRCode: typeof import('./src/components/QRCode.vue')['default']
    Receiver: typeof import('./src/components/Receiver.vue')['default']
    Sender: typeof import('./src/components/Sender.vue')['default']
  }
}
