name: Frontend CI

on:
  push:
    branches:
      - next
    paths-ignore:
      - .github/**
      - .vscode/**
      - src-backend/**
      - .gitignore
      - Cargo.lock
      - Cargo.toml
      - "!.github/workflows/frontend-ci.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: dist
